repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: bash -c 'for file in "$@"; do sed -i "s/[[:space:]]*$//" "$file"; done'
        language: system
        types: [text]

      - id: end-of-file-fixer
        name: fix end of files
        entry: python -c "import sys; [open(f, 'a').write('\\n') if open(f, 'rb').read() and not open(f, 'rb').read().endswith(b'\\n') else None for f in sys.argv[1:]]"
        language: system
        types: [text]

      - id: check-yaml
        name: check yaml
        entry: python -c "import sys, yaml; [yaml.safe_load(open(f)) for f in sys.argv[1:]]"
        language: system
        files: \.(yaml|yml)$

      - id: black
        name: black
        entry: black
        language: system
        args: [--safe, --quiet]
        files: ^custom_components/.*\.py$

      - id: isort
        name: isort
        entry: isort
        language: system
        args: [--profile, black]
        files: ^custom_components/.*\.py$

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        files: ^custom_components/.*\.py$

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: [--ignore-missing-imports]
        files: ^custom_components/.*\.py$
