import { defineConfig } from 'tsup'

export default defineConfig({
  // Entry points
  entry: ['src/index.ts'],
  
  // Output formats for dual module support
  format: ['cjs', 'esm'],
  
  // Generate type definitions
  dts: true,
  
  // Code splitting for better tree-shaking
  splitting: true,
  
  // Source maps for debugging
  sourcemap: true,
  
  // Clean dist folder before build
  clean: true,
  
  // Minify output for production
  minify: false, // Keep readable for now during development
  
  // Bundle external dependencies
  bundle: true,
  
  // Target modern environments
  target: 'es2022',
  
  // Output directory
  outDir: 'dist',
  
  // Keep original file names
  keepNames: true,
  
  // Tree shaking
  treeshake: true,
  
  // Platform targeting
  platform: 'neutral',
  
  // External dependencies (mark as external to avoid bundling)
  external: [],
  
  // Define build-time constants
  define: {
    __VERSION__: '"1.5.9"',
  },
  
  // Banner for generated files
  banner: {
    js: '// Generated by tsup - Home Assistant Anylist Integration TypeScript SDK',
  },
  
  // Custom esbuild options
  esbuildOptions: (options) => {
    // Ensure proper tree shaking
    options.treeShaking = true
    // Keep class names for better debugging
    options.keepNames = true
  },
})