name: CI

"on":
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup Matrix
    outputs:
      python-versions: ${{ steps.set-matrix.outputs.python-versions }}
    steps:
      - name: Set up Python version matrix
        id: set-matrix
        run: |
          echo 'python-versions=["3.11", "3.12", "3.13"]' >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: setup
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.setup.outputs.python-versions) }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy
          pip install homeassistant

      - name: Check code formatting with black
        run: black --check --diff custom_components/
      - name: Check import sorting with isort
        run: isort --check-only --diff custom_components/
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 custom_components/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. GitHub editor is 127 chars wide
          flake8 custom_components/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Type check with mypy
        run: mypy custom_components/ --ignore-missing-imports

  test:
    runs-on: ubuntu-latest
    needs: [setup, lint]
    name: Test
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.setup.outputs.python-versions) }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-homeassistant-custom-component
          pip install homeassistant

      - name: Run tests with pytest
        run: pytest tests/ -v
        continue-on-error: true

  hassfest:
    runs-on: ubuntu-latest
    name: Validate with hassfest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Validate integration with hassfest
        uses: home-assistant/actions/hassfest@master
        with:
          path: ./custom_components/anylist
